name: Run markdownlint

on:
  pull_request:
    branches: main
    types: ['opened', 'reopened', 'synchronize', 'ready_for_review']

jobs:
  lint-markdown:
    if: '! github.event.pull_request.draft'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker://avtodev/markdown-lint:v1
        with:
          config: '.markdownlint.json'
          args: '.'
