name: Publish article

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]
on:
  workflow_dispatch:

jobs:
  publish-test:
    uses: ./.github/workflows/run-check.yaml
    with:
      command: pnpm publish:test
