name: Run checks

on:
  pull_request:
    branches: main
    types: ['opened', 'edited', 'reopened', 'synchronize', 'ready_for_review']

jobs:
  lint:
    if: '! github.event.pull_request.draft'
    uses: ./.github/workflows/prepare.yaml
    with:
      command: pnpm lint
  test:
    if: '! github.event.pull_request.draft'
    uses: ./.github/workflows/prepare.yaml
    with:
      command: pnpm test:run
  build:
    if: '! github.event.pull_request.draft'
    uses: ./.github/workflows/prepare.yaml
    with:
      command: pnpm build
