name: Run checks

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize', 'ready_for_review']

jobs:
  typecheck:
    uses: ./.github/workflows/run-check.yaml
    with:
      command: bun tsc --noEmit
  lint:
    uses: ./.github/workflows/run-check.yaml
    with:
      command: bun lint
  test:
    uses: ./.github/workflows/run-check.yaml
    with:
      command: bun test
