name: Run check

on:
  workflow_call:
    inputs:
      command:
        required: true
        type: string

jobs:
  check:
    if: github.event_name != 'pull_request' || !github.event.pull_request.draft
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: ${{ inputs.command }}
