name: Run checks

on:
  pull_request:
    branches: main
    types: ['opened', 'reopened', 'synchronize', 'ready_for_review']

jobs:
  typecheck:
    uses: ./.github/workflows/run-check.yaml
    with:
      command: pnpm typecheck
  lint:
    uses: ./.github/workflows/run-check.yaml
    with:
      command: pnpm lint
  test:
    uses: ./.github/workflows/run-check.yaml
    with:
      command: pnpm test:run
