name: Run checks

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize', 'ready_for_review']

jobs:
  lint:
    uses: ./.github/workflows/run-check.yaml
    with:
      command: bun lint
  test:
    uses: ./.github/workflows/run-check.yaml
    with:
      command: bun test
  # build:
  #   uses: ./.github/workflows/run-check.yaml
  #   with:
  #     command: pnpm build
